apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8qzk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-8qzk@sha256:f455ebc16a28dd1e2e902c5f389854f87c370e7502df0a2fb119a715378a1589
        name: my-nodejs
        resources: {}
status: {}
